### PR TITLE
remove Python 3.7 support

### PR DESCRIPTION
**Pull request by BurnzZ**
Post-merge to-do:
- [ ] Merge https://github.com/zytedata/python-zyte-api/pull/47.

### CODE REVIEW

**Comment by kmike** [comment]
It'd be good to keep it a bit longer, because this change would mean dropping Python 3.7 support in https://github.com/scrapy-plugins/scrapy-zyte-api. How big is the issue you're facing with CI?

**Comment by BurnzZ** [comment]
> How big is the issue you're facing with CI?

Not that big for 3.7 with regards to https://github.com/zytedata/python-zyte-api/pull/52, which errors out since `AsyncMock` isn't available until 3.8 ([ref](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.AsyncMock)). If the other versions are passing in the CI, then I think we're good.

**Comment by Gallaecio** [comment]
https://github.com/zytedata/python-zyte-api/pull/47 also aims to use AsyncMock. May we resume this?

**Review by Gallaecio — APPROVED** [review]

**Comment by kmike** [comment]
I think we can drop 3.7 in both packages now.

**Pull request merged**
