### PR TITLE
Uncomment 520 retry code

### PR DESCRIPTION
**Pull request by Gallaecio**
Resolves #17

### CODE REVIEW

**Comment by Gallaecio** [comment]
Regarding https://github.com/scrapy-plugins/scrapy-zyte-api/issues/25, should this be enough (up to 15 minutes of retries), or should we do something else (e.g. allow customizing the `retrying` parameter of `AsyncClient.request_raw`, or expose failed requests to middlewares with metadata that reflects the retries done by the client).

**Comment by kmike** [comment]
As discussed elsewhere, we should make the default retries less aggressive (e.g. 3 retries). In future we could make it more configurable, e.g. like it was in [zyte-autoextract](https://github.com/zytedata/zyte-autoextract) library.

**Comment by Gallaecio** [comment]
```
$ echo <URL that triggers 520> | zyte-api -
INFO:zyte_api:Loaded 1 urls from <stdin>; shuffled: False
INFO:zyte_api:Running Zyte Data API (connections: 20)
  0%|                                                                                            | 0/1 [00:00<?, ?url/s, conn:0.00s, resp:0.00s, throttle:0.0%, err:0+0(0.0%) | success:0/0(0.0%)]ERROR:zyte_api:RequestError: 520, message=, headers=<CIMultiDictProxy('Date': 'Wed, 06 Jul 2022 17:20:08 GMT', 'Content-Type': 'application/problem+json', 'Content-Length': '162', 'Connection': 'keep-alive', 'Retry-After': '60', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=0; includeSubDomains; preload')>, body=b'{"type":"/download/temporary-error","title":"Temporary Downloading Error","status":520,"detail":"There is a downloading problem which might be temporary. Retry in N seconds from \'Retry-After\' header."}'
  0%|                                                                                         | 0/1 [01:43<?, ?url/s, conn:20.68s, resp:0.00s, throttle:0.0%, err:3+1(100.0%) | success:0/1(0.0%)]
INFO:zyte_api:
Summary
-------
Mean connection time:     20.68
Mean response time:       0.00
Throttle ratio:           0.0%
Attempts:                 4
Errors:                   100.0%, fatal: 1, non fatal: 3
Successful URLs:          0 of 1
Success ratio:            0.0%

INFO:zyte_api:
API error types:
[('/download/temporary-error', 4)]
INFO:zyte_api:
Status codes:
[(520, 4)]
INFO:zyte_api:
Exception types:
[]
```

**Comment by kmike** [comment]
It looks good for one request; how does it look like if another request is successful?

**Comment by Gallaecio** [comment]
```
$ echo "<URL that triggers 520>
> https://toscrape.com" | zyte-api -
INFO:zyte_api:Loaded 2 urls from <stdin>; shuffled: False
INFO:zyte_api:Running Zyte Data API (connections: 20)
  0%|                                                                                            | 0/2 [00:00<?, ?url/s, conn:0.00s, resp:0.00s, throttle:0.0%, err:0+0(0.0%) | success:0/0(0.0%)]{"url": "https://toscrape.com/", "browserHtml": "<!DOCTYPE html><html lang=\"en\"><head>\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n        <title>Scraping Sandbox</title>\n        <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n        <link href=\"./css/main.css\" rel=\"stylesheet\">\n    </head>\n    <body>\n        <div class=\"container\">\n            <div class=\"row\">\n                <div class=\"col-md-1\"></div>\n                <div class=\"col-md-10 well\">\n                    <img class=\"logo\" src=\"img/zyte.png\" width=\"200px\">\n                    <h1 class=\"text-right\">Web Scraping Sandbox</h1>\n                </div>\n            </div>\n\n            <div class=\"row\">\n                <div class=\"col-md-1\"></div>\n                <div class=\"col-md-10\">\n                    <h2>Books</h2>\n                    <p>A <a href=\"http://books.toscrape.com\">fictional bookstore</a> that desperately wants to be scraped. It's a safe place for beginners learning web scraping and for developers validating their scraping technologies as well. Available at: <a href=\"http://books.toscrape.com\">books.toscrape.com</a></p>\n                    <div class=\"col-md-6\">\n                        <a href=\"http://books.toscrape.com\"><img src=\"./img/books.png\" class=\"img-thumbnail\"></a>\n                    </div>\n                    <div class=\"col-md-6\">\n                        <table class=\"table table-hover\">\n                            <tbody><tr><th colspan=\"2\">Details</th></tr>\n                            <tr><td>Amount of items </td><td>1000</td></tr>\n                            <tr><td>Pagination </td><td>✔</td></tr>\n                            <tr><td>Items per page </td><td>max 20</td></tr>\n                            <tr><td>Requires JavaScript </td><td>✘</td></tr>\n                        </tbody></table>\n                    </div>\n                </div>\n            </div>\n\n            <div class=\"row\">\n                <div class=\"col-md-1\"></div>\n                <div class=\"col-md-10\">\n                    <h2>Quotes</h2>\n                    <p><a href=\"http://quotes.toscrape.com/\">A website</a> that lists quotes from famous people. It has many endpoints showing the quotes in many different ways, each of them including new scraping challenges for you, as described below.</p>\n                    <div class=\"col-md-6\">\n                        <a href=\"http://quotes.toscrape.com\"><img src=\"./img/quotes.png\" class=\"img-thumbnail\"></a>\n                    </div>\n                    <div class=\"col-md-6\">\n                        <table class=\"table table-hover\">\n                            <tbody><tr><th colspan=\"2\">Endpoints</th></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/\">Default</a></td><td>Microdata and pagination</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/scroll\">Scroll</a> </td><td>infinite scrolling pagination</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/js\">JavaScript</a> </td><td>JavaScript generated content</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/js-delayed\">Delayed</a> </td><td>Same as JavaScript but with a delay (?delay=10000)</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/tableful\">Tableful</a> </td><td>a table based messed-up layout</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/login\">Login</a> </td><td>login with CSRF token (any user/passwd works)</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/search.aspx\">ViewState</a> </td><td>an AJAX based filter form with ViewStates</td></tr>\n                            <tr><td><a href=\"http://quotes.toscrape.com/random\">Random</a> </td><td>a single random quote</td></tr>\n                        </tbody></table>\n                    </div>\n                </div>\n            </div>\n        </div>\n    \n\n</body></html>", "echoData": "https://toscrape.com"}
 50%|█████████████████████████████████████████                                         | 1/2 [00:08<00:08,  8.67s/url, conn:8.66s, resp:8.66s, throttle:0.0%, err:0+0(0.0%) | success:1/1(100.0%)]ERROR:zyte_api:RequestError: 520, message=, headers=<CIMultiDictProxy('Date': 'Thu, 07 Jul 2022 11:38:30 GMT', 'Content-Type': 'application/problem+json', 'Content-Length': '162', 'Connection': 'keep-alive', 'Retry-After': '60', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=0; includeSubDomains; preload')>, body=b'{"type":"/download/temporary-error","title":"Temporary Downloading Error","status":520,"detail":"There is a downloading problem which might be temporary. Retry in N seconds from \'Retry-After\' header."}'
 50%|████████████████████████████████████████                                        | 1/2 [01:43<01:43, 103.44s/url, conn:18.99s, resp:8.66s, throttle:0.0%, err:3+1(80.0%) | success:1/2(50.0%)]
INFO:zyte_api:
Summary
-------
Mean connection time:     18.99
Mean response time:       8.66
Throttle ratio:           0.0%
Attempts:                 5
Errors:                   80.0%, fatal: 1, non fatal: 3
Successful URLs:          1 of 2
Success ratio:            50.0%

INFO:zyte_api:
API error types:
[('/download/temporary-error', 4)]
INFO:zyte_api:
Status codes:
[(520, 4), (200, 1)]
INFO:zyte_api:
Exception types:
[]
```

**Comment by kmike** [comment]
Thanks @Gallaecio!

**Pull request merged**
